name: Build with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions: write-all

jobs:
  call-build:
    uses: trevorism/actions-workflows/.github/workflows/build.yml@master